package itip

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/hstern/go-mailbox-720/internal/calendar"
	"github.com/hstern/go-mailbox-720/internal/scheduling"
)

// fixedDate is the deterministic clock used for every composed message so the
// generated bytes (Date header, etc.) are reproducible.
var fixedDate = time.Date(2026, 6, 19, 9, 30, 0, 0, time.UTC)

// fakeWriter is a calendar.Writer that records the CreateEvent call instead of
// touching a backend. It stamps a synthetic ID on the returned event so callers
// can tell the stored event apart from the input.
type fakeWriter struct {
	createCalls int
	gotCalendar string
	gotEvent    calendar.Event
	createErr   error
}

func (f *fakeWriter) CreateEvent(_ context.Context, calendarID string, e calendar.Event) (calendar.Event, error) {
	f.createCalls++
	f.gotCalendar = calendarID
	f.gotEvent = e
	if f.createErr != nil {
		return calendar.Event{}, f.createErr
	}
	e.ID = "stored-id"
	e.CalendarID = calendarID
	return e, nil
}

func (f *fakeWriter) UpdateEvent(_ context.Context, e calendar.Event) (calendar.Event, error) {
	return e, nil
}

func (f *fakeWriter) DeleteEvent(_ context.Context, _ string) error { return nil }

// fakeSender is an smtp.Sender that records the envelope and raw bytes of the
// Send call instead of opening a connection.
type fakeSender struct {
	sendCalls int
	gotFrom   string
	gotTo     []string
	gotRaw    []byte
	sendErr   error
}

func (f *fakeSender) Send(_ context.Context, from string, to []string, raw []byte) error {
	f.sendCalls++
	f.gotFrom = from
	f.gotTo = to
	f.gotRaw = raw
	return f.sendErr
}

func (f *fakeSender) Close() error { return nil }

// sampleRequest builds a realistic raw iMIP REQUEST through the engine itself:
// Request() produces the VCALENDAR and Compose() wraps it in the RFC 822 message,
// so the bytes are exactly the shape Parse expects.
func sampleRequest(t *testing.T) []byte {
	t.Helper()
	inv := scheduling.Invite{
		UID:       "abc-123@example.com",
		Summary:   "Project sync",
		Start:     time.Date(2026, 6, 15, 15, 0, 0, 0, time.UTC),
		End:       time.Date(2026, 6, 15, 16, 0, 0, 0, time.UTC),
		Sequence:  2,
		Organizer: scheduling.Address{Name: "Olivia Organizer", Email: "olivia@example.com"},
		Attendees: []scheduling.Attendee{
			{Address: scheduling.Address{Name: "Andy Attendee", Email: "andy@example.com"}},
		},
	}
	ics, err := scheduling.Request(inv)
	if err != nil {
		t.Fatalf("build request ics: %v", err)
	}
	raw, err := scheduling.Compose(
		inv.Organizer,
		[]scheduling.Address{inv.Attendees[0].Address},
		"Invitation: "+inv.Summary,
		scheduling.MethodRequest,
		ics,
		fixedDate,
	)
	if err != nil {
		t.Fatalf("compose request message: %v", err)
	}
	return raw
}

func TestEventFromInvite(t *testing.T) {
	inv := &scheduling.Invite{
		UID:       "uid-1@example.com",
		Summary:   "Project sync",
		Start:     time.Date(2026, 6, 15, 15, 0, 0, 0, time.UTC),
		End:       time.Date(2026, 6, 15, 16, 0, 0, 0, time.UTC),
		Organizer: scheduling.Address{Name: "Olivia Organizer", Email: "olivia@example.com"},
		Attendees: []scheduling.Attendee{
			{Address: scheduling.Address{Name: "Andy", Email: "andy@example.com"}, PartStat: scheduling.PartStatNeedsAction},
			{Address: scheduling.Address{Name: "Bea", Email: "bea@example.com"}, PartStat: scheduling.PartStatNeedsAction},
		},
	}

	got := EventFromInvite(inv)

	if got.UID != inv.UID {
		t.Errorf("UID = %q, want %q", got.UID, inv.UID)
	}
	if got.Subject != inv.Summary {
		t.Errorf("Subject = %q, want %q", got.Subject, inv.Summary)
	}
	if !got.Start.Equal(inv.Start) {
		t.Errorf("Start = %v, want %v", got.Start, inv.Start)
	}
	if !got.End.Equal(inv.End) {
		t.Errorf("End = %v, want %v", got.End, inv.End)
	}
	if got.Status != StatusTentative {
		t.Errorf("Status = %q, want %q", got.Status, StatusTentative)
	}
	wantOrg := calendar.Address{Name: "Olivia Organizer", Email: "olivia@example.com"}
	if got.Organizer != wantOrg {
		t.Errorf("Organizer = %+v, want %+v", got.Organizer, wantOrg)
	}
	if len(got.Attendees) != 2 {
		t.Fatalf("Attendees len = %d, want 2", len(got.Attendees))
	}
	if got.Attendees[0] != (calendar.Address{Name: "Andy", Email: "andy@example.com"}) {
		t.Errorf("Attendees[0] = %+v", got.Attendees[0])
	}
	if got.Attendees[1] != (calendar.Address{Name: "Bea", Email: "bea@example.com"}) {
		t.Errorf("Attendees[1] = %+v", got.Attendees[1])
	}
}

func TestEventFromInviteNil(t *testing.T) {
	got := EventFromInvite(nil)
	if got.UID != "" || got.Subject != "" || got.Status != "" || len(got.Attendees) != 0 {
		t.Errorf("EventFromInvite(nil) = %+v, want zero-valued Event", got)
	}
}

func TestProcessRequest(t *testing.T) {
	raw := sampleRequest(t)
	w := &fakeWriter{}

	created, err := ProcessRequest(context.Background(), w, "cal-1", raw)
	if err != nil {
		t.Fatalf("ProcessRequest: %v", err)
	}

	if w.createCalls != 1 {
		t.Fatalf("CreateEvent calls = %d, want 1", w.createCalls)
	}
	if w.gotCalendar != "cal-1" {
		t.Errorf("calendarID = %q, want cal-1", w.gotCalendar)
	}
	if w.gotEvent.Status != StatusTentative {
		t.Errorf("created event Status = %q, want %q", w.gotEvent.Status, StatusTentative)
	}
	if w.gotEvent.UID != "abc-123@example.com" {
		t.Errorf("created event UID = %q", w.gotEvent.UID)
	}
	if w.gotEvent.Subject != "Project sync" {
		t.Errorf("created event Subject = %q", w.gotEvent.Subject)
	}
	if w.gotEvent.Organizer.Email != "olivia@example.com" {
		t.Errorf("created event Organizer = %+v", w.gotEvent.Organizer)
	}
	if len(w.gotEvent.Attendees) != 1 || w.gotEvent.Attendees[0].Email != "andy@example.com" {
		t.Errorf("created event Attendees = %+v", w.gotEvent.Attendees)
	}
	// The returned event is the store's stamped copy.
	if created.ID != "stored-id" {
		t.Errorf("returned event ID = %q, want stored-id", created.ID)
	}
}

func TestProcessRequestRejectsNonRequest(t *testing.T) {
	// Build a REPLY iMIP via the engine and feed it to ProcessRequest.
	req, err := scheduling.Parse(sampleRequest(t))
	if err != nil {
		t.Fatalf("parse sample: %v", err)
	}
	replyMsg, err := scheduling.ComposeReply(
		req,
		scheduling.Address{Name: "Andy Attendee", Email: "andy@example.com"},
		scheduling.PartStatAccepted,
		fixedDate,
	)
	if err != nil {
		t.Fatalf("compose reply: %v", err)
	}

	w := &fakeWriter{}
	_, err = ProcessRequest(context.Background(), w, "cal-1", replyMsg)
	if err == nil {
		t.Fatal("ProcessRequest on a REPLY: want error, got nil")
	}
	if w.createCalls != 0 {
		t.Errorf("CreateEvent calls = %d, want 0 on rejected method", w.createCalls)
	}
}

func TestProcessRequestParseError(t *testing.T) {
	w := &fakeWriter{}
	_, err := ProcessRequest(context.Background(), w, "cal-1", []byte("not a message"))
	if err == nil {
		t.Fatal("want parse error, got nil")
	}
	if w.createCalls != 0 {
		t.Errorf("CreateEvent calls = %d, want 0", w.createCalls)
	}
}

func TestProcessRequestWriterError(t *testing.T) {
	w := &fakeWriter{createErr: errors.New("backend down")}
	_, err := ProcessRequest(context.Background(), w, "cal-1", sampleRequest(t))
	if err == nil {
		t.Fatal("want writer error, got nil")
	}
}

func TestRespond(t *testing.T) {
	raw := sampleRequest(t)
	s := &fakeSender{}
	attendee := scheduling.Address{Name: "Andy Attendee", Email: "andy@example.com"}

	err := Respond(context.Background(), s, attendee, scheduling.PartStatAccepted, raw, fixedDate)
	if err != nil {
		t.Fatalf("Respond: %v", err)
	}

	if s.sendCalls != 1 {
		t.Fatalf("Send calls = %d, want 1", s.sendCalls)
	}
	if s.gotFrom != "andy@example.com" {
		t.Errorf("from = %q, want andy@example.com", s.gotFrom)
	}
	if len(s.gotTo) != 1 || s.gotTo[0] != "olivia@example.com" {
		t.Errorf("to = %v, want [olivia@example.com]", s.gotTo)
	}

	// The sent bytes must Parse back to a REPLY carrying the attendee's decision.
	reply, err := scheduling.Parse(s.gotRaw)
	if err != nil {
		t.Fatalf("parse sent reply: %v", err)
	}
	if reply.Method != scheduling.MethodReply {
		t.Errorf("sent method = %q, want REPLY", reply.Method)
	}
	if len(reply.Attendees) != 1 {
		t.Fatalf("reply attendees = %d, want 1", len(reply.Attendees))
	}
	if reply.Attendees[0].PartStat != scheduling.PartStatAccepted {
		t.Errorf("reply PARTSTAT = %q, want ACCEPTED", reply.Attendees[0].PartStat)
	}
	if reply.Attendees[0].Email != "andy@example.com" {
		t.Errorf("reply attendee = %q", reply.Attendees[0].Email)
	}
}

func TestRespondPartStats(t *testing.T) {
	raw := sampleRequest(t)
	attendee := scheduling.Address{Name: "Andy Attendee", Email: "andy@example.com"}

	for _, ps := range []scheduling.PartStat{
		scheduling.PartStatAccepted,
		scheduling.PartStatDeclined,
		scheduling.PartStatTentative,
	} {
		t.Run(string(ps), func(t *testing.T) {
			s := &fakeSender{}
			if err := Respond(context.Background(), s, attendee, ps, raw, fixedDate); err != nil {
				t.Fatalf("Respond: %v", err)
			}
			reply, err := scheduling.Parse(s.gotRaw)
			if err != nil {
				t.Fatalf("parse reply: %v", err)
			}
			if reply.Attendees[0].PartStat != ps {
				t.Errorf("PARTSTAT = %q, want %q", reply.Attendees[0].PartStat, ps)
			}
		})
	}
}

func TestRespondNoOrganizer(t *testing.T) {
	// A REQUEST with no ORGANIZER cannot be replied to. Build one by hand: the
	// engine's Request() requires an organizer, so construct the message directly.
	ics := "BEGIN:VCALENDAR\r\n" +
		"VERSION:2.0\r\n" +
		"PRODID:-//Example//EN\r\n" +
		"METHOD:REQUEST\r\n" +
		"BEGIN:VEVENT\r\n" +
		"UID:no-org@example.com\r\n" +
		"DTSTAMP:20260601T120000Z\r\n" +
		"DTSTART:20260615T150000Z\r\n" +
		"SUMMARY:Orphan invite\r\n" +
		"ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:andy@example.com\r\n" +
		"END:VEVENT\r\n" +
		"END:VCALENDAR\r\n"
	raw := rawMessage(ics)

	s := &fakeSender{}
	err := Respond(context.Background(), s, scheduling.Address{Email: "andy@example.com"}, scheduling.PartStatAccepted, raw, fixedDate)
	if err == nil {
		t.Fatal("Respond without organizer: want error, got nil")
	}
	if s.sendCalls != 0 {
		t.Errorf("Send calls = %d, want 0", s.sendCalls)
	}
}

func TestRespondSenderError(t *testing.T) {
	s := &fakeSender{sendErr: errors.New("smtp down")}
	attendee := scheduling.Address{Email: "andy@example.com"}
	err := Respond(context.Background(), s, attendee, scheduling.PartStatAccepted, sampleRequest(t), fixedDate)
	if err == nil {
		t.Fatal("want sender error, got nil")
	}
}

func TestInvite(t *testing.T) {
	inv := &scheduling.Invite{
		UID:       "new-1@example.com",
		Summary:   "Kickoff",
		Start:     time.Date(2026, 7, 1, 14, 0, 0, 0, time.UTC),
		End:       time.Date(2026, 7, 1, 15, 0, 0, 0, time.UTC),
		Sequence:  0,
		Organizer: scheduling.Address{Name: "Olivia", Email: "olivia@example.com"},
		Attendees: []scheduling.Attendee{
			{Address: scheduling.Address{Email: "andy@example.com"}},
			{Address: scheduling.Address{Email: "bea@example.com"}},
		},
	}
	organizer := scheduling.Address{Name: "Olivia", Email: "olivia@example.com"}

	s := &fakeSender{}
	if err := Invite(context.Background(), s, organizer, inv, fixedDate); err != nil {
		t.Fatalf("Invite: %v", err)
	}

	if s.sendCalls != 1 {
		t.Fatalf("Send calls = %d, want 1", s.sendCalls)
	}
	if s.gotFrom != "olivia@example.com" {
		t.Errorf("from = %q, want olivia@example.com", s.gotFrom)
	}
	if len(s.gotTo) != 2 || s.gotTo[0] != "andy@example.com" || s.gotTo[1] != "bea@example.com" {
		t.Errorf("to = %v, want [andy bea]", s.gotTo)
	}

	req, err := scheduling.Parse(s.gotRaw)
	if err != nil {
		t.Fatalf("parse sent request: %v", err)
	}
	if req.Method != scheduling.MethodRequest {
		t.Errorf("sent method = %q, want REQUEST", req.Method)
	}
	if req.UID != "new-1@example.com" {
		t.Errorf("sent UID = %q", req.UID)
	}
	if len(req.Attendees) != 2 {
		t.Errorf("sent attendees = %d, want 2", len(req.Attendees))
	}
}

func TestInviteNil(t *testing.T) {
	s := &fakeSender{}
	if err := Invite(context.Background(), s, scheduling.Address{Email: "olivia@example.com"}, nil, fixedDate); err == nil {
		t.Fatal("Invite(nil): want error, got nil")
	}
}

// rawMessage wraps an iCalendar body in a minimal multipart/mixed RFC 822 iMIP
// message so Parse can find the text/calendar part. Used for hand-built invites
// the engine's generators would reject.
func rawMessage(ics string) []byte {
	const boundary = "b0undary"
	return []byte("From: olivia@example.com\r\n" +
		"To: andy@example.com\r\n" +
		"Subject: Invite\r\n" +
		"MIME-Version: 1.0\r\n" +
		"Content-Type: multipart/mixed; boundary=\"" + boundary + "\"\r\n" +
		"\r\n" +
		"--" + boundary + "\r\n" +
		"Content-Type: text/calendar; method=REQUEST; charset=utf-8\r\n\r\n" +
		ics +
		"\r\n--" + boundary + "--\r\n")
}
