package itip

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/hstern/go-jscalendar"
	"github.com/hstern/go-mailbox-720/internal/calendar"
	"github.com/hstern/go-mailbox-720/internal/scheduling"
)

// recurrenceIDInstant resolves a calendar.Event's RecurrenceID (a JSCalendar
// LocalDateTime + zone) back to the UTC instant the iCalendar RECURRENCE-ID
// encoded, for comparison in tests.
func recurrenceIDInstant(ev calendar.Event) (time.Time, bool) {
	if ev.RecurrenceID == nil {
		return time.Time{}, false
	}
	return recurrenceIDToTime(ev.RecurrenceID, ev.RecurrenceIDTimeZone), true
}

// fixedDate is the deterministic clock used for every composed message so the
// generated bytes (Date header, etc.) are reproducible.
var fixedDate = time.Date(2026, 6, 19, 9, 30, 0, 0, time.UTC)

// fakeWriter is a calendar.Writer that records the CreateEvent call instead of
// touching a backend. It stamps a synthetic ID on the returned event so callers
// can tell the stored event apart from the input.
type fakeWriter struct {
	createCalls int
	gotCalendar string
	gotEvent    calendar.Event
	createErr   error
}

func (f *fakeWriter) CreateEvent(_ context.Context, calendarID string, e calendar.Event) (calendar.Event, error) {
	f.createCalls++
	f.gotCalendar = calendarID
	f.gotEvent = e
	if f.createErr != nil {
		return calendar.Event{}, f.createErr
	}
	e.ID = "stored-id"
	e.CalendarID = calendarID
	return e, nil
}

func (f *fakeWriter) UpdateEvent(_ context.Context, e calendar.Event) (calendar.Event, error) {
	return e, nil
}

func (f *fakeWriter) DeleteEvent(_ context.Context, _ string) error { return nil }

// fakeSender is an smtp.Sender that records the envelope and raw bytes of the
// Send call instead of opening a connection.
type fakeSender struct {
	sendCalls int
	gotFrom   string
	gotTo     []string
	gotRaw    []byte
	sendErr   error
}

func (f *fakeSender) Send(_ context.Context, from string, to []string, raw []byte) error {
	f.sendCalls++
	f.gotFrom = from
	f.gotTo = to
	f.gotRaw = raw
	return f.sendErr
}

func (f *fakeSender) Close() error { return nil }

// sampleRequest builds a realistic raw iMIP REQUEST through the engine itself:
// Request() produces the VCALENDAR and Compose() wraps it in the RFC 822 message,
// so the bytes are exactly the shape Parse expects.
func sampleRequest(t *testing.T) []byte {
	t.Helper()
	inv := scheduling.Invite{
		UID:       "abc-123@example.com",
		Summary:   "Project sync",
		Start:     time.Date(2026, 6, 15, 15, 0, 0, 0, time.UTC),
		End:       time.Date(2026, 6, 15, 16, 0, 0, 0, time.UTC),
		Sequence:  2,
		Organizer: scheduling.Address{Name: "Olivia Organizer", Email: "olivia@example.com"},
		Attendees: []scheduling.Attendee{
			{Address: scheduling.Address{Name: "Andy Attendee", Email: "andy@example.com"}},
		},
	}
	ics, err := scheduling.Request(inv)
	if err != nil {
		t.Fatalf("build request ics: %v", err)
	}
	raw, err := scheduling.Compose(
		inv.Organizer,
		[]scheduling.Address{inv.Attendees[0].Address},
		"Invitation: "+inv.Summary,
		scheduling.MethodRequest,
		ics,
		fixedDate,
	)
	if err != nil {
		t.Fatalf("compose request message: %v", err)
	}
	return raw
}

func TestEventFromInvite(t *testing.T) {
	inv := &scheduling.Invite{
		UID:       "uid-1@example.com",
		Summary:   "Project sync",
		Start:     time.Date(2026, 6, 15, 15, 0, 0, 0, time.UTC),
		End:       time.Date(2026, 6, 15, 16, 0, 0, 0, time.UTC),
		Organizer: scheduling.Address{Name: "Olivia Organizer", Email: "olivia@example.com"},
		Attendees: []scheduling.Attendee{
			{Address: scheduling.Address{Name: "Andy", Email: "andy@example.com"}, PartStat: scheduling.PartStatNeedsAction},
			{Address: scheduling.Address{Name: "Bea", Email: "bea@example.com"}, PartStat: scheduling.PartStatNeedsAction},
		},
	}

	got := EventFromInvite(inv)

	if got.UID != inv.UID {
		t.Errorf("UID = %q, want %q", got.UID, inv.UID)
	}
	if got.Title != inv.Summary {
		t.Errorf("Title = %q, want %q", got.Title, inv.Summary)
	}
	if !got.StartTime().Equal(inv.Start) {
		t.Errorf("StartTime = %v, want %v", got.StartTime(), inv.Start)
	}
	if !got.EndTime().Equal(inv.End) {
		t.Errorf("EndTime = %v, want %v", got.EndTime(), inv.End)
	}
	if got.Status != StatusTentative {
		t.Errorf("Status = %q, want %q", got.Status, StatusTentative)
	}
	org, ok := got.Organizer()
	if !ok {
		t.Fatal("Organizer() not found, want Olivia Organizer")
	}
	if org.Name != "Olivia Organizer" || calendar.ParticipantEmail(org) != "olivia@example.com" {
		t.Errorf("Organizer = name=%q email=%q", org.Name, calendar.ParticipantEmail(org))
	}
	atts := got.Attendees()
	if len(atts) != 2 {
		t.Fatalf("Attendees len = %d, want 2", len(atts))
	}
	wantAtt := []struct{ name, email string }{
		{"Andy", "andy@example.com"},
		{"Bea", "bea@example.com"},
	}
	for i, w := range wantAtt {
		if atts[i].Name != w.name || calendar.ParticipantEmail(atts[i]) != w.email {
			t.Errorf("Attendees[%d] = name=%q email=%q, want %q/%q",
				i, atts[i].Name, calendar.ParticipantEmail(atts[i]), w.name, w.email)
		}
		if atts[i].ParticipationStatus != "needs-action" {
			t.Errorf("Attendees[%d] partStat = %q, want needs-action", i, atts[i].ParticipationStatus)
		}
	}
}

func TestEventFromInviteNil(t *testing.T) {
	got := EventFromInvite(nil)
	if got.UID != "" || got.Title != "" || got.Status != "" || len(got.Attendees()) != 0 {
		t.Errorf("EventFromInvite(nil) = %+v, want zero-valued Event", got)
	}
}

func TestProcessRequest(t *testing.T) {
	raw := sampleRequest(t)
	w := &fakeWriter{}

	created, err := ProcessRequest(context.Background(), w, "cal-1", raw)
	if err != nil {
		t.Fatalf("ProcessRequest: %v", err)
	}

	if w.createCalls != 1 {
		t.Fatalf("CreateEvent calls = %d, want 1", w.createCalls)
	}
	if w.gotCalendar != "cal-1" {
		t.Errorf("calendarID = %q, want cal-1", w.gotCalendar)
	}
	if w.gotEvent.Status != StatusTentative {
		t.Errorf("created event Status = %q, want %q", w.gotEvent.Status, StatusTentative)
	}
	if w.gotEvent.UID != "abc-123@example.com" {
		t.Errorf("created event UID = %q", w.gotEvent.UID)
	}
	if w.gotEvent.Title != "Project sync" {
		t.Errorf("created event Title = %q", w.gotEvent.Title)
	}
	if org, ok := w.gotEvent.Organizer(); !ok || calendar.ParticipantEmail(org) != "olivia@example.com" {
		t.Errorf("created event Organizer = %+v", org)
	}
	gotAtts := w.gotEvent.Attendees()
	if len(gotAtts) != 1 || calendar.ParticipantEmail(gotAtts[0]) != "andy@example.com" {
		t.Errorf("created event Attendees = %+v", gotAtts)
	}
	// The returned event is the store's stamped copy.
	if created.ID != "stored-id" {
		t.Errorf("returned event ID = %q, want stored-id", created.ID)
	}
}

func TestProcessRequestRejectsNonRequest(t *testing.T) {
	// Build a REPLY iMIP via the engine and feed it to ProcessRequest.
	req, err := scheduling.Parse(sampleRequest(t))
	if err != nil {
		t.Fatalf("parse sample: %v", err)
	}
	replyMsg, err := scheduling.ComposeReply(
		req,
		scheduling.Address{Name: "Andy Attendee", Email: "andy@example.com"},
		scheduling.PartStatAccepted,
		fixedDate,
	)
	if err != nil {
		t.Fatalf("compose reply: %v", err)
	}

	w := &fakeWriter{}
	_, err = ProcessRequest(context.Background(), w, "cal-1", replyMsg)
	if err == nil {
		t.Fatal("ProcessRequest on a REPLY: want error, got nil")
	}
	if w.createCalls != 0 {
		t.Errorf("CreateEvent calls = %d, want 0 on rejected method", w.createCalls)
	}
}

func TestProcessRequestParseError(t *testing.T) {
	w := &fakeWriter{}
	_, err := ProcessRequest(context.Background(), w, "cal-1", []byte("not a message"))
	if err == nil {
		t.Fatal("want parse error, got nil")
	}
	if w.createCalls != 0 {
		t.Errorf("CreateEvent calls = %d, want 0", w.createCalls)
	}
}

func TestProcessRequestWriterError(t *testing.T) {
	w := &fakeWriter{createErr: errors.New("backend down")}
	_, err := ProcessRequest(context.Background(), w, "cal-1", sampleRequest(t))
	if err == nil {
		t.Fatal("want writer error, got nil")
	}
}

func TestRespond(t *testing.T) {
	raw := sampleRequest(t)
	s := &fakeSender{}
	attendee := scheduling.Address{Name: "Andy Attendee", Email: "andy@example.com"}

	err := Respond(context.Background(), s, attendee, scheduling.PartStatAccepted, raw, fixedDate)
	if err != nil {
		t.Fatalf("Respond: %v", err)
	}

	if s.sendCalls != 1 {
		t.Fatalf("Send calls = %d, want 1", s.sendCalls)
	}
	if s.gotFrom != "andy@example.com" {
		t.Errorf("from = %q, want andy@example.com", s.gotFrom)
	}
	if len(s.gotTo) != 1 || s.gotTo[0] != "olivia@example.com" {
		t.Errorf("to = %v, want [olivia@example.com]", s.gotTo)
	}

	// The sent bytes must Parse back to a REPLY carrying the attendee's decision.
	reply, err := scheduling.Parse(s.gotRaw)
	if err != nil {
		t.Fatalf("parse sent reply: %v", err)
	}
	if reply.Method != scheduling.MethodReply {
		t.Errorf("sent method = %q, want REPLY", reply.Method)
	}
	if len(reply.Attendees) != 1 {
		t.Fatalf("reply attendees = %d, want 1", len(reply.Attendees))
	}
	if reply.Attendees[0].PartStat != scheduling.PartStatAccepted {
		t.Errorf("reply PARTSTAT = %q, want ACCEPTED", reply.Attendees[0].PartStat)
	}
	if reply.Attendees[0].Email != "andy@example.com" {
		t.Errorf("reply attendee = %q", reply.Attendees[0].Email)
	}
}

func TestRespondPartStats(t *testing.T) {
	raw := sampleRequest(t)
	attendee := scheduling.Address{Name: "Andy Attendee", Email: "andy@example.com"}

	for _, ps := range []scheduling.PartStat{
		scheduling.PartStatAccepted,
		scheduling.PartStatDeclined,
		scheduling.PartStatTentative,
	} {
		t.Run(string(ps), func(t *testing.T) {
			s := &fakeSender{}
			if err := Respond(context.Background(), s, attendee, ps, raw, fixedDate); err != nil {
				t.Fatalf("Respond: %v", err)
			}
			reply, err := scheduling.Parse(s.gotRaw)
			if err != nil {
				t.Fatalf("parse reply: %v", err)
			}
			if reply.Attendees[0].PartStat != ps {
				t.Errorf("PARTSTAT = %q, want %q", reply.Attendees[0].PartStat, ps)
			}
		})
	}
}

func TestRespondNoOrganizer(t *testing.T) {
	// A REQUEST with no ORGANIZER cannot be replied to. Build one by hand: the
	// engine's Request() requires an organizer, so construct the message directly.
	ics := "BEGIN:VCALENDAR\r\n" +
		"VERSION:2.0\r\n" +
		"PRODID:-//Example//EN\r\n" +
		"METHOD:REQUEST\r\n" +
		"BEGIN:VEVENT\r\n" +
		"UID:no-org@example.com\r\n" +
		"DTSTAMP:20260601T120000Z\r\n" +
		"DTSTART:20260615T150000Z\r\n" +
		"SUMMARY:Orphan invite\r\n" +
		"ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:andy@example.com\r\n" +
		"END:VEVENT\r\n" +
		"END:VCALENDAR\r\n"
	raw := rawMessage(ics)

	s := &fakeSender{}
	err := Respond(context.Background(), s, scheduling.Address{Email: "andy@example.com"}, scheduling.PartStatAccepted, raw, fixedDate)
	if err == nil {
		t.Fatal("Respond without organizer: want error, got nil")
	}
	if s.sendCalls != 0 {
		t.Errorf("Send calls = %d, want 0", s.sendCalls)
	}
}

func TestRespondSenderError(t *testing.T) {
	s := &fakeSender{sendErr: errors.New("smtp down")}
	attendee := scheduling.Address{Email: "andy@example.com"}
	err := Respond(context.Background(), s, attendee, scheduling.PartStatAccepted, sampleRequest(t), fixedDate)
	if err == nil {
		t.Fatal("want sender error, got nil")
	}
}

// sampleEvent builds a stored calendar.Event of the shape the future
// accept/decline endpoints would load: an organizer to reply to and a couple of
// attendees, with no original REQUEST mail retained.
func sampleEvent() calendar.Event {
	var ev calendar.Event
	ev.UID = "evt-123@example.com"
	ev.Title = "Project sync"
	ev.SetUTCTimes(
		time.Date(2026, 6, 15, 15, 0, 0, 0, time.UTC),
		time.Date(2026, 6, 15, 16, 0, 0, 0, time.UTC),
	)
	org := calendar.NewParticipant("Olivia Organizer", "org@example.com", "", "owner")
	ev.SetOrganizerAttendees(&org, []jscalendar.Participant{
		calendar.NewParticipant("Andy Attendee", "andy@example.com", "", "attendee"),
		calendar.NewParticipant("Bea Attendee", "bea@example.com", "", "attendee"),
	})
	return ev
}

func TestInviteFromEvent(t *testing.T) {
	ev := sampleEvent()
	ev.Sequence = 5

	got := InviteFromEvent(ev)

	if got.Method != scheduling.MethodRequest {
		t.Errorf("Method = %q, want REQUEST", got.Method)
	}
	if got.UID != ev.UID {
		t.Errorf("UID = %q, want %q", got.UID, ev.UID)
	}
	if got.Summary != ev.Title {
		t.Errorf("Summary = %q, want %q", got.Summary, ev.Title)
	}
	if !got.Start.Equal(ev.StartTime()) {
		t.Errorf("Start = %v, want %v", got.Start, ev.StartTime())
	}
	if !got.End.Equal(ev.EndTime()) {
		t.Errorf("End = %v, want %v", got.End, ev.EndTime())
	}
	wantOrg := scheduling.Address{Name: "Olivia Organizer", Email: "org@example.com"}
	if got.Organizer != wantOrg {
		t.Errorf("Organizer = %+v, want %+v", got.Organizer, wantOrg)
	}
	if len(got.Attendees) != 2 {
		t.Fatalf("Attendees len = %d, want 2", len(got.Attendees))
	}
	for i, want := range []scheduling.Attendee{
		{Address: scheduling.Address{Name: "Andy Attendee", Email: "andy@example.com"}},
		{Address: scheduling.Address{Name: "Bea Attendee", Email: "bea@example.com"}},
	} {
		if got.Attendees[i] != want {
			t.Errorf("Attendees[%d] = %+v, want %+v (empty PARTSTAT)", i, got.Attendees[i], want)
		}
	}
	if got.Sequence != 5 {
		t.Errorf("Sequence = %d, want 5 (carried from the event)", got.Sequence)
	}
	// A master event (no RecurrenceID) yields an invite addressing the whole series.
	if got.RecurrenceID != "" {
		t.Errorf("RecurrenceID = %q, want empty for a master event", got.RecurrenceID)
	}
}

// InviteFromEvent threads a non-zero RecurrenceID through to the invite so the
// REPLY/REQUEST/CANCEL it backs targets a single occurrence of a series.
func TestInviteFromEventRecurrenceID(t *testing.T) {
	ev := sampleEvent()
	rid := localDateTimeUTC(time.Date(2026, 6, 22, 9, 0, 0, 0, time.UTC))
	ev.RecurrenceID = &rid
	ev.RecurrenceIDTimeZone = "Etc/UTC"

	got := InviteFromEvent(ev)

	if got.RecurrenceID != "20260622T090000Z" {
		t.Errorf("RecurrenceID = %q, want 20260622T090000Z", got.RecurrenceID)
	}
	// The reply echoes the RECURRENCE-ID, so the composed REPLY carries it.
	reply, err := scheduling.Reply(got, scheduling.Address{Email: "a@example.com"}, scheduling.PartStatAccepted)
	if err != nil {
		t.Fatalf("Reply: %v", err)
	}
	if !strings.Contains(string(reply), "RECURRENCE-ID") {
		t.Errorf("composed REPLY missing RECURRENCE-ID:\n%s", reply)
	}
}

// EventFromInvite parses a RECURRENCE-ID off an inbound invite into the neutral
// event's RecurrenceID, marking it an override.
func TestEventFromInviteRecurrenceID(t *testing.T) {
	inv := &scheduling.Invite{
		Method:  scheduling.MethodRequest,
		UID:     "series@example.com",
		Summary: "Standup",
		Start:   time.Date(2026, 6, 22, 10, 30, 0, 0, time.UTC),
	}
	inv.SetRecurrenceID(time.Date(2026, 6, 22, 9, 0, 0, 0, time.UTC))

	ev := EventFromInvite(inv)

	want := time.Date(2026, 6, 22, 9, 0, 0, 0, time.UTC)
	got, ok := recurrenceIDInstant(ev)
	if !ok || !got.Equal(want) {
		t.Errorf("RecurrenceID = %v (ok=%v), want %v", got, ok, want)
	}
	if !ev.IsOverride {
		t.Error("IsOverride = false, want true for an instance REQUEST")
	}
}

func TestRespondToEvent(t *testing.T) {
	ev := sampleEvent()
	s := &fakeSender{}
	attendee := scheduling.Address{Name: "Andy Attendee", Email: "andy@example.com"}

	err := RespondToEvent(context.Background(), s, ev, attendee, scheduling.PartStatAccepted, fixedDate)
	if err != nil {
		t.Fatalf("RespondToEvent: %v", err)
	}

	if s.sendCalls != 1 {
		t.Fatalf("Send calls = %d, want 1", s.sendCalls)
	}
	if s.gotFrom != "andy@example.com" {
		t.Errorf("from = %q, want andy@example.com", s.gotFrom)
	}
	if len(s.gotTo) != 1 || s.gotTo[0] != "org@example.com" {
		t.Errorf("to = %v, want [org@example.com]", s.gotTo)
	}

	// The sent bytes must Parse back to a REPLY carrying the attendee's decision.
	reply, err := scheduling.Parse(s.gotRaw)
	if err != nil {
		t.Fatalf("parse sent reply: %v", err)
	}
	if reply.Method != scheduling.MethodReply {
		t.Errorf("sent method = %q, want REPLY", reply.Method)
	}
	if reply.UID != "evt-123@example.com" {
		t.Errorf("reply UID = %q, want evt-123@example.com", reply.UID)
	}
	if len(reply.Attendees) != 1 {
		t.Fatalf("reply attendees = %d, want 1", len(reply.Attendees))
	}
	if reply.Attendees[0].Email != "andy@example.com" {
		t.Errorf("reply attendee = %q", reply.Attendees[0].Email)
	}
	if reply.Attendees[0].PartStat != scheduling.PartStatAccepted {
		t.Errorf("reply PARTSTAT = %q, want ACCEPTED", reply.Attendees[0].PartStat)
	}
}

func TestRespondToEventPartStats(t *testing.T) {
	ev := sampleEvent()
	attendee := scheduling.Address{Name: "Andy Attendee", Email: "andy@example.com"}

	for _, ps := range []scheduling.PartStat{
		scheduling.PartStatAccepted,
		scheduling.PartStatDeclined,
		scheduling.PartStatTentative,
	} {
		t.Run(string(ps), func(t *testing.T) {
			s := &fakeSender{}
			if err := RespondToEvent(context.Background(), s, ev, attendee, ps, fixedDate); err != nil {
				t.Fatalf("RespondToEvent: %v", err)
			}
			if s.gotFrom != "andy@example.com" {
				t.Errorf("from = %q, want andy@example.com", s.gotFrom)
			}
			if len(s.gotTo) != 1 || s.gotTo[0] != "org@example.com" {
				t.Errorf("to = %v, want [org@example.com]", s.gotTo)
			}
			reply, err := scheduling.Parse(s.gotRaw)
			if err != nil {
				t.Fatalf("parse reply: %v", err)
			}
			if reply.Method != scheduling.MethodReply {
				t.Errorf("method = %q, want REPLY", reply.Method)
			}
			if reply.Attendees[0].PartStat != ps {
				t.Errorf("PARTSTAT = %q, want %q", reply.Attendees[0].PartStat, ps)
			}
		})
	}
}

func TestRespondToEventNoOrganizer(t *testing.T) {
	ev := sampleEvent()
	// Drop the owner-role participant so the event has no organizer to reply to.
	ev.SetOrganizerAttendees(nil, []jscalendar.Participant{
		calendar.NewParticipant("Andy Attendee", "andy@example.com", "", "attendee"),
		calendar.NewParticipant("Bea Attendee", "bea@example.com", "", "attendee"),
	})

	s := &fakeSender{}
	err := RespondToEvent(context.Background(), s, ev, scheduling.Address{Email: "andy@example.com"}, scheduling.PartStatAccepted, fixedDate)
	if err == nil {
		t.Fatal("RespondToEvent without organizer: want error, got nil")
	}
	if s.sendCalls != 0 {
		t.Errorf("Send calls = %d, want 0", s.sendCalls)
	}
}

func TestRespondToEventSenderError(t *testing.T) {
	s := &fakeSender{sendErr: errors.New("smtp down")}
	attendee := scheduling.Address{Email: "andy@example.com"}
	err := RespondToEvent(context.Background(), s, sampleEvent(), attendee, scheduling.PartStatAccepted, fixedDate)
	if err == nil {
		t.Fatal("want sender error, got nil")
	}
}

func TestInvite(t *testing.T) {
	inv := &scheduling.Invite{
		UID:       "new-1@example.com",
		Summary:   "Kickoff",
		Start:     time.Date(2026, 7, 1, 14, 0, 0, 0, time.UTC),
		End:       time.Date(2026, 7, 1, 15, 0, 0, 0, time.UTC),
		Sequence:  0,
		Organizer: scheduling.Address{Name: "Olivia", Email: "olivia@example.com"},
		Attendees: []scheduling.Attendee{
			{Address: scheduling.Address{Email: "andy@example.com"}},
			{Address: scheduling.Address{Email: "bea@example.com"}},
		},
	}
	organizer := scheduling.Address{Name: "Olivia", Email: "olivia@example.com"}

	s := &fakeSender{}
	if err := Invite(context.Background(), s, organizer, inv, fixedDate); err != nil {
		t.Fatalf("Invite: %v", err)
	}

	if s.sendCalls != 1 {
		t.Fatalf("Send calls = %d, want 1", s.sendCalls)
	}
	if s.gotFrom != "olivia@example.com" {
		t.Errorf("from = %q, want olivia@example.com", s.gotFrom)
	}
	if len(s.gotTo) != 2 || s.gotTo[0] != "andy@example.com" || s.gotTo[1] != "bea@example.com" {
		t.Errorf("to = %v, want [andy bea]", s.gotTo)
	}

	req, err := scheduling.Parse(s.gotRaw)
	if err != nil {
		t.Fatalf("parse sent request: %v", err)
	}
	if req.Method != scheduling.MethodRequest {
		t.Errorf("sent method = %q, want REQUEST", req.Method)
	}
	if req.UID != "new-1@example.com" {
		t.Errorf("sent UID = %q", req.UID)
	}
	if len(req.Attendees) != 2 {
		t.Errorf("sent attendees = %d, want 2", len(req.Attendees))
	}
}

func TestInviteNil(t *testing.T) {
	s := &fakeSender{}
	if err := Invite(context.Background(), s, scheduling.Address{Email: "olivia@example.com"}, nil, fixedDate); err == nil {
		t.Fatal("Invite(nil): want error, got nil")
	}
}

// rawMessage wraps an iCalendar body in a minimal multipart/mixed RFC 822 iMIP
// message so Parse can find the text/calendar part. Used for hand-built invites
// the engine's generators would reject.
func rawMessage(ics string) []byte {
	const boundary = "b0undary"
	return []byte("From: olivia@example.com\r\n" +
		"To: andy@example.com\r\n" +
		"Subject: Invite\r\n" +
		"MIME-Version: 1.0\r\n" +
		"Content-Type: multipart/mixed; boundary=\"" + boundary + "\"\r\n" +
		"\r\n" +
		"--" + boundary + "\r\n" +
		"Content-Type: text/calendar; method=REQUEST; charset=utf-8\r\n\r\n" +
		ics +
		"\r\n--" + boundary + "--\r\n")
}

func TestCancel(t *testing.T) {
	inv := &scheduling.Invite{
		UID:       "old-1@example.com",
		Summary:   "Kickoff",
		Start:     time.Date(2026, 7, 1, 14, 0, 0, 0, time.UTC),
		Sequence:  0,
		Organizer: scheduling.Address{Name: "Olivia", Email: "olivia@example.com"},
		Attendees: []scheduling.Attendee{
			{Address: scheduling.Address{Email: "andy@example.com"}},
			{Address: scheduling.Address{Email: "bea@example.com"}},
		},
	}
	organizer := scheduling.Address{Name: "Olivia", Email: "olivia@example.com"}

	s := &fakeSender{}
	if err := Cancel(context.Background(), s, organizer, inv, fixedDate); err != nil {
		t.Fatalf("Cancel: %v", err)
	}
	if s.sendCalls != 1 {
		t.Fatalf("Send calls = %d, want 1", s.sendCalls)
	}
	if s.gotFrom != "olivia@example.com" {
		t.Errorf("from = %q, want olivia@example.com", s.gotFrom)
	}
	if len(s.gotTo) != 2 || s.gotTo[0] != "andy@example.com" || s.gotTo[1] != "bea@example.com" {
		t.Errorf("to = %v, want [andy bea]", s.gotTo)
	}

	cancel, err := scheduling.Parse(s.gotRaw)
	if err != nil {
		t.Fatalf("parse sent cancel: %v", err)
	}
	if cancel.Method != scheduling.MethodCancel {
		t.Errorf("sent method = %q, want CANCEL", cancel.Method)
	}
	if cancel.UID != "old-1@example.com" {
		t.Errorf("sent UID = %q, want old-1@example.com", cancel.UID)
	}
}

func TestCancelNil(t *testing.T) {
	s := &fakeSender{}
	if err := Cancel(context.Background(), s, scheduling.Address{Email: "olivia@example.com"}, nil, fixedDate); err == nil {
		t.Fatal("Cancel(nil): want error, got nil")
	}
}

// fakeFinderWriter is a calendar.Writer + calendar.Finder for the UID-correlation
// tests: FindEventByUID returns a preset event, and it records whether the inbound
// REQUEST resulted in a create, an update, or neither.
type fakeFinderWriter struct {
	existing  calendar.Event
	found     bool
	created   bool
	updated   bool
	updatedEv calendar.Event
}

// storedEvent builds a calendar.Event with the embedded jscalendar.Event fields
// (UID, Sequence) set — they cannot be named in a composite literal once the
// embedding hides them behind the outer struct.
func storedEvent(id, uid string, seq uint) calendar.Event {
	var ev calendar.Event
	ev.ID = id
	ev.UID = uid
	ev.Sequence = seq
	return ev
}

func (f *fakeFinderWriter) FindEventByUID(context.Context, string, string) (calendar.Event, bool, error) {
	return f.existing, f.found, nil
}
func (f *fakeFinderWriter) CreateEvent(_ context.Context, calendarID string, e calendar.Event) (calendar.Event, error) {
	f.created = true
	e.ID = "created-id"
	return e, nil
}
func (f *fakeFinderWriter) UpdateEvent(_ context.Context, e calendar.Event) (calendar.Event, error) {
	f.updated = true
	f.updatedEv = e
	return e, nil
}
func (f *fakeFinderWriter) DeleteEvent(context.Context, string) error { return nil }

// requestWithSequence builds an inbound REQUEST iMIP message at a given SEQUENCE
// (UID abc-123@example.com), for the UID-correlation tests.
func requestWithSequence(t *testing.T, seq int) []byte {
	t.Helper()
	inv := scheduling.Invite{
		UID:       "abc-123@example.com",
		Summary:   "Project sync",
		Start:     time.Date(2026, 6, 15, 15, 0, 0, 0, time.UTC),
		End:       time.Date(2026, 6, 15, 16, 0, 0, 0, time.UTC),
		Sequence:  seq,
		Organizer: scheduling.Address{Email: "olivia@example.com"},
		Attendees: []scheduling.Attendee{{Address: scheduling.Address{Email: "andy@example.com"}}},
	}
	ics, err := scheduling.Request(inv)
	if err != nil {
		t.Fatalf("build request ics: %v", err)
	}
	raw, err := scheduling.Compose(inv.Organizer, []scheduling.Address{inv.Attendees[0].Address},
		"Invitation", scheduling.MethodRequest, ics, fixedDate)
	if err != nil {
		t.Fatalf("compose request message: %v", err)
	}
	return raw
}

// No existing event for the UID: ProcessRequest creates (the first-cut behavior).
func TestProcessRequestUnknownUIDCreates(t *testing.T) {
	w := &fakeFinderWriter{found: false}
	if _, err := ProcessRequest(context.Background(), w, "cal-1", requestWithSequence(t, 0)); err != nil {
		t.Fatalf("ProcessRequest: %v", err)
	}
	if !w.created || w.updated {
		t.Errorf("created=%v updated=%v, want create only", w.created, w.updated)
	}
}

// A re-sent REQUEST at a higher SEQUENCE updates the existing event in place rather
// than creating a duplicate.
func TestProcessRequestHigherSequenceUpdatesInPlace(t *testing.T) {
	w := &fakeFinderWriter{found: true, existing: storedEvent("evt-stored", "abc-123@example.com", 1)}
	if _, err := ProcessRequest(context.Background(), w, "cal-1", requestWithSequence(t, 2)); err != nil {
		t.Fatalf("ProcessRequest: %v", err)
	}
	if w.created || !w.updated {
		t.Errorf("created=%v updated=%v, want update only", w.created, w.updated)
	}
	if w.updatedEv.ID != "evt-stored" {
		t.Errorf("updated event ID = %q, want evt-stored (updated in place)", w.updatedEv.ID)
	}
	if w.updatedEv.Sequence != 2 {
		t.Errorf("updated SEQUENCE = %d, want 2", w.updatedEv.Sequence)
	}
}

// A re-delivered (equal) or stale (lower) SEQUENCE neither creates nor updates —
// it leaves the stored event and the attendee's own PARTSTAT untouched.
func TestProcessRequestEqualOrLowerSequenceSkips(t *testing.T) {
	for _, tc := range []struct {
		name             string
		stored, incoming int
	}{
		{"equal/duplicate", 2, 2},
		{"lower/stale", 3, 2},
	} {
		t.Run(tc.name, func(t *testing.T) {
			w := &fakeFinderWriter{found: true, existing: storedEvent("evt-stored", "abc-123@example.com", uint(tc.stored))}
			got, err := ProcessRequest(context.Background(), w, "cal-1", requestWithSequence(t, tc.incoming))
			if err != nil {
				t.Fatalf("ProcessRequest: %v", err)
			}
			if w.created || w.updated {
				t.Errorf("created=%v updated=%v, want neither", w.created, w.updated)
			}
			if got.ID != "evt-stored" {
				t.Errorf("returned event ID = %q, want the stored event unchanged", got.ID)
			}
		})
	}
}

// fakeInstanceWriter is a Finder + Writer + InstanceWriter that records the
// instance-override path of ProcessRequest.
type fakeInstanceWriter struct {
	fakeFinderWriter
	overrideMasterID string
	overrideEv       calendar.Event
	overrideWritten  bool
}

func (f *fakeInstanceWriter) WriteInstanceOverride(_ context.Context, masterID string, e calendar.Event) (calendar.Event, error) {
	f.overrideWritten = true
	f.overrideMasterID = masterID
	f.overrideEv = e
	e.ID = "override-id"
	e.SeriesMasterID = masterID
	return e, nil
}

// requestForInstance builds an inbound REQUEST iMIP message carrying a
// RECURRENCE-ID — an organizer re-inviting a single occurrence of a series.
func requestForInstance(t *testing.T, recurrenceID time.Time) []byte {
	t.Helper()
	inv := scheduling.Invite{
		UID:       "abc-123@example.com",
		Summary:   "Project sync (moved)",
		Start:     time.Date(2026, 6, 22, 17, 0, 0, 0, time.UTC),
		End:       time.Date(2026, 6, 22, 18, 0, 0, 0, time.UTC),
		Organizer: scheduling.Address{Email: "olivia@example.com"},
		Attendees: []scheduling.Attendee{{Address: scheduling.Address{Email: "andy@example.com"}}},
	}
	inv.SetRecurrenceID(recurrenceID)
	ics, err := scheduling.Request(inv)
	if err != nil {
		t.Fatalf("build request ics: %v", err)
	}
	raw, err := scheduling.Compose(inv.Organizer, []scheduling.Address{inv.Attendees[0].Address},
		"Invitation", scheduling.MethodRequest, ics, fixedDate)
	if err != nil {
		t.Fatalf("compose request message: %v", err)
	}
	return raw
}

// A single-instance REQUEST against a backend with InstanceWriter records a
// per-occurrence override on the located series master, not a standalone event.
func TestProcessRequestInstanceOverride(t *testing.T) {
	rid := time.Date(2026, 6, 22, 15, 0, 0, 0, time.UTC)
	w := &fakeInstanceWriter{fakeFinderWriter: fakeFinderWriter{
		found:    true,
		existing: storedEvent("master-id", "abc-123@example.com", 0),
	}}

	got, err := ProcessRequest(context.Background(), w, "cal-1", requestForInstance(t, rid))
	if err != nil {
		t.Fatalf("ProcessRequest: %v", err)
	}
	if !w.overrideWritten {
		t.Fatal("WriteInstanceOverride not called for an instance REQUEST")
	}
	if w.created || w.updated {
		t.Errorf("created=%v updated=%v, want neither for the override path", w.created, w.updated)
	}
	if w.overrideMasterID != "master-id" {
		t.Errorf("override master ID = %q, want master-id", w.overrideMasterID)
	}
	if got, ok := recurrenceIDInstant(w.overrideEv); !ok || !got.Equal(rid) {
		t.Errorf("override RecurrenceID = %v (ok=%v), want %v", got, ok, rid)
	}
	if got.SeriesMasterID != "master-id" {
		t.Errorf("returned SeriesMasterID = %q, want master-id", got.SeriesMasterID)
	}
}

// Without InstanceWriter, a single-instance REQUEST falls back to the standard
// create path (surfacing the occurrence as its own tentative event).
func TestProcessRequestInstanceFallbackCreates(t *testing.T) {
	rid := time.Date(2026, 6, 22, 15, 0, 0, 0, time.UTC)
	w := &fakeFinderWriter{found: true, existing: storedEvent("master-id", "abc-123@example.com", 0)}

	if _, err := ProcessRequest(context.Background(), w, "cal-1", requestForInstance(t, rid)); err != nil {
		t.Fatalf("ProcessRequest: %v", err)
	}
	// found=true with seq 0 <= existing 0 means the standard path skips as a
	// duplicate; the key assertion is no panic and no override path. Confirm it did
	// not update in place with a stale sequence either.
	if w.updated {
		t.Error("updated in place; want the standard UID-correlation path, not an override")
	}
}
